local wk = require("which-key").add
vim.g.mapleader = " "

wk {
	{ "t",       "j",                desc = '',        expr = false, nowait = false, remap = false },
	{ "n",       "k",                desc = '',        expr = false, nowait = false, remap = false },
	{ "s",       "l",                desc = '',        expr = false, nowait = false, remap = false },
	{ "k",       "n",                desc = '',        expr = false, nowait = false, remap = false },
	{ "T",       "J",                desc = '',        expr = false, nowait = false, remap = false },
	{ "N",       "K",                desc = '',        expr = false, nowait = false, remap = false },
	{ "S",       "L",                desc = '',        expr = false, nowait = false, remap = false },
	{ "K",       "N",                desc = '',        expr = false, nowait = false, remap = false },
	{ "<C-h>",   ":wincmd h <CR>",   desc = '',        expr = false, nowait = false, remap = false },
	{ "<C-t>",   ":wincmd j <CR>",   desc = '',        expr = false, nowait = false, remap = false },
	{ "<C-n>",   ":wincmd k <CR>",   desc = '',        expr = false, nowait = false, remap = false },
	{ "<C-s>",   ":wincmd l <CR>",   desc = '',        expr = false, nowait = false, remap = false },
	{ "<C-[>",   '<C-f>zz<CR>',      desc = '',        expr = false, nowait = false, remap = false },
	{ "<C-]>",   '<C-b>zz<CR>',      desc = '',        expr = false, nowait = false, remap = false },
	{ "<C-a>",   ':wall<CR>',        desc = '',        expr = false, nowait = false, remap = false },
	{ "<C-z>",   ':qa<CR>',          desc = '',        expr = false, nowait = false, remap = false },
	{ "<C-q>",   ':bd!<CR>',         desc = '',        expr = false, nowait = false, remap = false },
	{ "<C-A-H>", ":nohlsearch<CR>",  desc = '',        expr = false, nowait = false, remap = false },
	{ "Y",       '"+y',              desc = '',        expr = false, nowait = false, remap = false },
	{ "<C-y>",   "y$",               desc = '',        expr = false, nowait = false, remap = false, mode = "v" },
	{ "t",       "j",                desc = '',        expr = false, nowait = false, remap = false, mode = "v" },
	{ "n",       "k",                desc = '',        expr = false, nowait = false, remap = false, mode = "v" },
	{ "s",       "l",                desc = '',        expr = false, nowait = false, remap = false, mode = "v" },
	{ "k",       "n",                desc = '',        expr = false, nowait = false, remap = false, mode = "v" },
	{ "T",       "J",                desc = '',        expr = false, nowait = false, remap = false, mode = "v" },
	{ "N",       "K",                desc = '',        expr = false, nowait = false, remap = false, mode = "v" },
	{ "S",       "L",                desc = '',        expr = false, nowait = false, remap = false, mode = "v" },
	{ "K",       "N",                desc = '',        expr = false, nowait = false, remap = false, mode = "v" },
	{ "<C-h>",   ":wincmd h <CR>",   desc = '',        expr = false, nowait = false, remap = false, mode = "t" },
	{ "<C-t>",   ":wincmd j <CR>",   desc = '',        expr = false, nowait = false, remap = false, mode = "t" },
	{ "<C-n>",   ":wincmd k <CR>",   desc = '',        expr = false, nowait = false, remap = false, mode = "t" },
	{ "<C-s>",   ":wincmd l <CR>",   desc = '',        expr = false, nowait = false, remap = false, mode = "t" },
	{ "<C-A-r>", "<cmd>restart<CR>", desc = 'Restart', expr = false, nowait = false, remap = false },
}
